name: 'publish'
on:
  push:
    branches: [main]
jobs:
  publish-tauri:
    permissions:
      contents: write
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: dtolnay/rust-toolchain@stable
      - run: npm install
      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: app-v1.0.3
          releaseName: 'App v1.0.3'
          releaseDraft: true
      - name: upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: INSTALADOR-MAC-AQUI
          path: src-tauri/target/release/bundle/dmg/*.dmg
